### ISSUE TITLE
"should"  sentences are not shown in outputs.

### ISSUE THREAD

**Issue by veracosta** [hiracy/serverspec-runner#25]
In my environment, every sentences beginning with "should" are not shown in outputs.

Here's an example.
I wrote spec file as follows.
```ruby
require 'spec_helper'
describe "test rsyslog service" do
  describe service('rsyslog') do
    it { should be_enabled }
    it { should be_running }
  end
end
describe "test rsyslog service" do
  describe command('chronyc sources') do
    its(:stdout) { should match /^\^\*/ }
  end
end
```
Then ran serverspec-runner with markdown table format
```
serverspec-runner -t mkd
```
Finally I've got the following output that all of should~ descriptions are missing.

|description                                                                                  | result |
|:--------------------------------------------------------------------------------------------|:------:|
|  test rsyslog service                                                        |        |
|    Service "rsyslog"                                                                        |        |
|                                                                                             |   OK   |
|                                                                                             |   OK   |
|  test rsyslog service                                                                    |        |
|    Command "chronyc sources"                                                                |        |
|      stdout                                                                                 |        |
|                                                                                             |   OK   |

Here's my environment.
```
$ rake --version
rake, version 10.4.2
$ rspec --version
3.2.0
$ ruby -v
ruby 2.0.0p353 (2013-11-22) [x86_64-linux]
$ cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)
```
I haven't edited any for spec_helper.rb.
Please let me know if I am missing something.
Regards.

**Comment by hiracy** [comment]
Sorry. I fix this bug at ver 1.1.7(652050).
Perhaps, it was caused by the change of the following RSpec :: Core.

https://github.com/rspec/rspec-core/commit/abd83d29fa55daf9e8c85a630a55c6f393086b22
