### ISSUE TITLE
Rakefile error

### ISSUE THREAD

**Issue by perfecto25** [hiracy/serverspec-runner#35]
running with ruby 1.8.7, centos 6

[root@mrxmaster vagrant]# serverspec-runner
/usr/lib/ruby/gems/1.8/gems/serverspec-runner-1.2.2/bin/../Rakefile:26: undefined method `exists?' for Dir:Class (NoMethodError)
	from /usr/lib/ruby/gems/1.8/gems/rake-10.3.2/lib/rake/task_manager.rb:209:in `in_namespace'
	from /usr/lib/ruby/gems/1.8/gems/rake-10.3.2/lib/rake/dsl_definition.rb:146:in `namespace'
	from /usr/lib/ruby/gems/1.8/gems/serverspec-runner-1.2.2/bin/../Rakefile:14
	from /usr/lib/ruby/gems/1.8/gems/serverspec-runner-1.2.2/bin/serverspec-runner:61:in `load'
	from /usr/lib/ruby/gems/1.8/gems/serverspec-runner-1.2.2/bin/serverspec-runner:61
	from /usr/bin/serverspec-runner:19:in `load'
	from /usr/bin/serverspec-runner:19

**Comment by hiracy** [comment]
serverspec-runner does not support less than 1.9 ruby. Please upgrade ruby to 1.9 or higher and use it.

**Comment by hiracy** [comment]
serverspec-runner will upgrade even the local ruby version and will not ask for the remote ruby version.
Please upgrade ruby to 1.9 or higher and use it.
